#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DangKyQuanLyMonHoc")]
	public partial class QLDangKyMonHocDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChuongTrinhDaoTao(ChuongTrinhDaoTao instance);
    partial void UpdateChuongTrinhDaoTao(ChuongTrinhDaoTao instance);
    partial void DeleteChuongTrinhDaoTao(ChuongTrinhDaoTao instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertDangKy(DangKy instance);
    partial void UpdateDangKy(DangKy instance);
    partial void DeleteDangKy(DangKy instance);
    partial void InsertDanhSachKhongDuocDangKy(DanhSachKhongDuocDangKy instance);
    partial void UpdateDanhSachKhongDuocDangKy(DanhSachKhongDuocDangKy instance);
    partial void DeleteDanhSachKhongDuocDangKy(DanhSachKhongDuocDangKy instance);
    partial void InsertDanhSachMon(DanhSachMon instance);
    partial void UpdateDanhSachMon(DanhSachMon instance);
    partial void DeleteDanhSachMon(DanhSachMon instance);
    partial void InsertGiaoVien(GiaoVien instance);
    partial void UpdateGiaoVien(GiaoVien instance);
    partial void DeleteGiaoVien(GiaoVien instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertLopHocPhan(LopHocPhan instance);
    partial void UpdateLopHocPhan(LopHocPhan instance);
    partial void DeleteLopHocPhan(LopHocPhan instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public QLDangKyMonHocDataContext() : 
				base(global::DoAnCuoiKi.Properties.Settings.Default.DangKyQuanLyMonHocConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDangKyMonHocDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDangKyMonHocDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDangKyMonHocDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDangKyMonHocDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChuongTrinhDaoTao> ChuongTrinhDaoTaos
		{
			get
			{
				return this.GetTable<ChuongTrinhDaoTao>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<DangKy> DangKies
		{
			get
			{
				return this.GetTable<DangKy>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachKhongDuocDangKy> DanhSachKhongDuocDangKies
		{
			get
			{
				return this.GetTable<DanhSachKhongDuocDangKy>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachMon> DanhSachMons
		{
			get
			{
				return this.GetTable<DanhSachMon>();
			}
		}
		
		public System.Data.Linq.Table<GiaoVien> GiaoViens
		{
			get
			{
				return this.GetTable<GiaoVien>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<LopHocPhan> LopHocPhans
		{
			get
			{
				return this.GetTable<LopHocPhan>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tklhptenmon", IsComposable=true)]
		public IQueryable<tklhptenmonResult> tklhptenmon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenmon)
		{
			return this.CreateMethodCallQuery<tklhptenmonResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenmon);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem", IsComposable=true)]
		public IQueryable<timkiemResult> timkiem()
		{
			return this.CreateMethodCallQuery<timkiemResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tklhpkhoa", IsComposable=true)]
		public IQueryable<tklhpkhoaResult> tklhpkhoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string tenkhoa)
		{
			return this.CreateMethodCallQuery<tklhpkhoaResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenkhoa);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tklhpmamon", IsComposable=true)]
		public IQueryable<tklhpmamonResult> tklhpmamon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string mamon)
		{
			return this.CreateMethodCallQuery<tklhpmamonResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mamon);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Dang_ky_mon_hoc")]
		public int Dang_ky_mon_hoc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maSV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV, maLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Them_lop_hoc_phan")]
		public int Them_lop_hoc_phan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string phongHoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(15)")] string thu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tuTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> denTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maGV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tgBatDau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon, phongHoc, thu, tuTiet, denTiet, maGV, soLuong, tgBatDau);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Chuong_trinh_ngoai_ke_hoach", IsComposable=true)]
		public IQueryable<Chuong_trinh_ngoai_ke_hoachResult> Chuong_trinh_ngoai_ke_hoach([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string sv)
		{
			return this.CreateMethodCallQuery<Chuong_trinh_ngoai_ke_hoachResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sv);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Chuong_trinh_dao_tao", IsComposable=true)]
		public IQueryable<Chuong_trinh_dao_taoResult> Chuong_trinh_dao_tao([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string sv)
		{
			return this.CreateMethodCallQuery<Chuong_trinh_dao_taoResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sv);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Chuong_trinh_theo_ke_hoach", IsComposable=true)]
		public IQueryable<Chuong_trinh_theo_ke_hoachResult> Chuong_trinh_theo_ke_hoach([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string sv)
		{
			return this.CreateMethodCallQuery<Chuong_trinh_theo_ke_hoachResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sv);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mon_dang_ky", IsComposable=true)]
		public IQueryable<Mon_dang_kyResult> Mon_dang_ky([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maSV)
		{
			return this.CreateMethodCallQuery<Mon_dang_kyResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themlophp")]
		public int themlophp([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string phongHoc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thu", DbType="NChar(15)")] string thu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuTiet", DbType="Int")] System.Nullable<int> tuTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenTiet", DbType="Int")] System.Nullable<int> denTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maGV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> daDK, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tgBatDau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tgKetThuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, maMon, phongHoc, thu, tuTiet, denTiet, maGV, soLuong, daDK, tgBatDau, tgKetThuc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editlhp")]
		public int editlhp([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string phongHoc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Thu", DbType="NChar(15)")] string thu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuTiet", DbType="Int")] System.Nullable<int> tuTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenTiet", DbType="Int")] System.Nullable<int> denTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string maGV, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tgBatDau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> tgKetThuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, maMon, phongHoc, thu, tuTiet, denTiet, maGV, soLuong, tgBatDau, tgKetThuc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dskhongdk", IsComposable=true)]
		public IQueryable<dskhongdkResult> dskhongdk()
		{
			return this.CreateMethodCallQuery<dskhongdkResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deletesvkodk")]
		public int deletesvkodk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string masv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), masv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editsvkodk")]
		public int editsvkodk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string masv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), masv, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addsvkodk")]
		public int addsvkodk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string masv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), masv, ghichu);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuongTrinhDaoTao")]
	public partial class ChuongTrinhDaoTao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maMon;
		
		private string _maKhoa;
		
		private EntityRef<DanhSachMon> _DanhSachMon;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaMonChanging(string value);
    partial void OnmaMonChanged();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    #endregion
		
		public ChuongTrinhDaoTao()
		{
			this._DanhSachMon = default(EntityRef<DanhSachMon>);
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					if (this._DanhSachMon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonChanging(value);
					this.SendPropertyChanging();
					this._maMon = value;
					this.SendPropertyChanged("maMon");
					this.OnmaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachMon_ChuongTrinhDaoTao", Storage="_DanhSachMon", ThisKey="maMon", OtherKey="maMon", IsForeignKey=true)]
		public DanhSachMon DanhSachMon
		{
			get
			{
				return this._DanhSachMon.Entity;
			}
			set
			{
				DanhSachMon previousValue = this._DanhSachMon.Entity;
				if (((previousValue != value) 
							|| (this._DanhSachMon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhSachMon.Entity = null;
						previousValue.ChuongTrinhDaoTaos.Remove(this);
					}
					this._DanhSachMon.Entity = value;
					if ((value != null))
					{
						value.ChuongTrinhDaoTaos.Add(this);
						this._maMon = value.maMon;
					}
					else
					{
						this._maMon = default(string);
					}
					this.SendPropertyChanged("DanhSachMon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_ChuongTrinhDaoTao", Storage="_Khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.ChuongTrinhDaoTaos.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.ChuongTrinhDaoTaos.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenDangNhap;
		
		private string _matkhau;
		
		private char _quyenDangNhap;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenDangNhapChanging(string value);
    partial void OntenDangNhapChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnquyenDangNhapChanging(char value);
    partial void OnquyenDangNhapChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDangNhap", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenDangNhap
		{
			get
			{
				return this._tenDangNhap;
			}
			set
			{
				if ((this._tenDangNhap != value))
				{
					this.OntenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._tenDangNhap = value;
					this.SendPropertyChanged("tenDangNhap");
					this.OntenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyenDangNhap", DbType="NChar(1) NOT NULL")]
		public char quyenDangNhap
		{
			get
			{
				return this._quyenDangNhap;
			}
			set
			{
				if ((this._quyenDangNhap != value))
				{
					this.OnquyenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._quyenDangNhap = value;
					this.SendPropertyChanged("quyenDangNhap");
					this.OnquyenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_SinhVien", Storage="_SinhVien", ThisKey="tenDangNhap", OtherKey="maSV", IsUnique=true, IsForeignKey=false)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.TaiKhoan = null;
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan = this;
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKy")]
	public partial class DangKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSV;
		
		private string _maLop;
		
		private string _maMon;
		
		private EntityRef<LopHocPhan> _LopHocPhan;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OnmaLopChanging(string value);
    partial void OnmaLopChanged();
    partial void OnmaMonChanging(string value);
    partial void OnmaMonChanged();
    #endregion
		
		public DangKy()
		{
			this._LopHocPhan = default(EntityRef<LopHocPhan>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					if (this._LopHocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this.OnmaMonChanging(value);
					this.SendPropertyChanging();
					this._maMon = value;
					this.SendPropertyChanged("maMon");
					this.OnmaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHocPhan_DangKy", Storage="_LopHocPhan", ThisKey="maLop", OtherKey="maLop", IsForeignKey=true)]
		public LopHocPhan LopHocPhan
		{
			get
			{
				return this._LopHocPhan.Entity;
			}
			set
			{
				LopHocPhan previousValue = this._LopHocPhan.Entity;
				if (((previousValue != value) 
							|| (this._LopHocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LopHocPhan.Entity = null;
						previousValue.DangKies.Remove(this);
					}
					this._LopHocPhan.Entity = value;
					if ((value != null))
					{
						value.DangKies.Add(this);
						this._maLop = value.maLop;
					}
					else
					{
						this._maLop = default(string);
					}
					this.SendPropertyChanged("LopHocPhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DangKy", Storage="_SinhVien", ThisKey="maSV", OtherKey="maSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.DangKies.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.DangKies.Add(this);
						this._maSV = value.maSV;
					}
					else
					{
						this._maSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachKhongDuocDangKy")]
	public partial class DanhSachKhongDuocDangKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSV;
		
		private string _ghiChu;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public DanhSachKhongDuocDangKy()
		{
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DanhSachKhongDuocDangKy", Storage="_SinhVien", ThisKey="maSV", OtherKey="maSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.DanhSachKhongDuocDangKy = null;
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.DanhSachKhongDuocDangKy = this;
						this._maSV = value.maSV;
					}
					else
					{
						this._maSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachMon")]
	public partial class DanhSachMon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maMon;
		
		private string _tenMon;
		
		private string _loaiMon;
		
		private int _soTC;
		
		private EntitySet<ChuongTrinhDaoTao> _ChuongTrinhDaoTaos;
		
		private EntitySet<LopHocPhan> _LopHocPhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaMonChanging(string value);
    partial void OnmaMonChanged();
    partial void OntenMonChanging(string value);
    partial void OntenMonChanged();
    partial void OnloaiMonChanging(string value);
    partial void OnloaiMonChanged();
    partial void OnsoTCChanging(int value);
    partial void OnsoTCChanged();
    #endregion
		
		public DanhSachMon()
		{
			this._ChuongTrinhDaoTaos = new EntitySet<ChuongTrinhDaoTao>(new Action<ChuongTrinhDaoTao>(this.attach_ChuongTrinhDaoTaos), new Action<ChuongTrinhDaoTao>(this.detach_ChuongTrinhDaoTaos));
			this._LopHocPhans = new EntitySet<LopHocPhan>(new Action<LopHocPhan>(this.attach_LopHocPhans), new Action<LopHocPhan>(this.detach_LopHocPhans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this.OnmaMonChanging(value);
					this.SendPropertyChanging();
					this._maMon = value;
					this.SendPropertyChanged("maMon");
					this.OnmaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this.OntenMonChanging(value);
					this.SendPropertyChanging();
					this._tenMon = value;
					this.SendPropertyChanged("tenMon");
					this.OntenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string loaiMon
		{
			get
			{
				return this._loaiMon;
			}
			set
			{
				if ((this._loaiMon != value))
				{
					this.OnloaiMonChanging(value);
					this.SendPropertyChanging();
					this._loaiMon = value;
					this.SendPropertyChanged("loaiMon");
					this.OnloaiMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this.OnsoTCChanging(value);
					this.SendPropertyChanging();
					this._soTC = value;
					this.SendPropertyChanged("soTC");
					this.OnsoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachMon_ChuongTrinhDaoTao", Storage="_ChuongTrinhDaoTaos", ThisKey="maMon", OtherKey="maMon")]
		public EntitySet<ChuongTrinhDaoTao> ChuongTrinhDaoTaos
		{
			get
			{
				return this._ChuongTrinhDaoTaos;
			}
			set
			{
				this._ChuongTrinhDaoTaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachMon_LopHocPhan", Storage="_LopHocPhans", ThisKey="maMon", OtherKey="maMon")]
		public EntitySet<LopHocPhan> LopHocPhans
		{
			get
			{
				return this._LopHocPhans;
			}
			set
			{
				this._LopHocPhans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachMon = this;
		}
		
		private void detach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachMon = null;
		}
		
		private void attach_LopHocPhans(LopHocPhan entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachMon = this;
		}
		
		private void detach_LopHocPhans(LopHocPhan entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachMon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoVien")]
	public partial class GiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maGV;
		
		private string _TenGV;
		
		private string _maKhoa;
		
		private EntitySet<LopHocPhan> _LopHocPhans;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGVChanging(string value);
    partial void OnmaGVChanged();
    partial void OnTenGVChanging(string value);
    partial void OnTenGVChanged();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    #endregion
		
		public GiaoVien()
		{
			this._LopHocPhans = new EntitySet<LopHocPhan>(new Action<LopHocPhan>(this.attach_LopHocPhans), new Action<LopHocPhan>(this.detach_LopHocPhans));
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGV
		{
			get
			{
				return this._TenGV;
			}
			set
			{
				if ((this._TenGV != value))
				{
					this.OnTenGVChanging(value);
					this.SendPropertyChanging();
					this._TenGV = value;
					this.SendPropertyChanged("TenGV");
					this.OnTenGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_LopHocPhan", Storage="_LopHocPhans", ThisKey="maGV", OtherKey="maGV")]
		public EntitySet<LopHocPhan> LopHocPhans
		{
			get
			{
				return this._LopHocPhans;
			}
			set
			{
				this._LopHocPhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiaoVien", Storage="_Khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LopHocPhans(LopHocPhan entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = this;
		}
		
		private void detach_LopHocPhans(LopHocPhan entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhoa;
		
		private string _tenKhoa;
		
		private EntitySet<ChuongTrinhDaoTao> _ChuongTrinhDaoTaos;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    partial void OntenKhoaChanging(string value);
    partial void OntenKhoaChanged();
    #endregion
		
		public Khoa()
		{
			this._ChuongTrinhDaoTaos = new EntitySet<ChuongTrinhDaoTao>(new Action<ChuongTrinhDaoTao>(this.attach_ChuongTrinhDaoTaos), new Action<ChuongTrinhDaoTao>(this.detach_ChuongTrinhDaoTaos));
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhoa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenKhoa
		{
			get
			{
				return this._tenKhoa;
			}
			set
			{
				if ((this._tenKhoa != value))
				{
					this.OntenKhoaChanging(value);
					this.SendPropertyChanging();
					this._tenKhoa = value;
					this.SendPropertyChanged("tenKhoa");
					this.OntenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_ChuongTrinhDaoTao", Storage="_ChuongTrinhDaoTaos", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<ChuongTrinhDaoTao> ChuongTrinhDaoTaos
		{
			get
			{
				return this._ChuongTrinhDaoTaos;
			}
			set
			{
				this._ChuongTrinhDaoTaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiaoVien", Storage="_GiaoViens", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_SinhViens", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_ChuongTrinhDaoTaos(ChuongTrinhDaoTao entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LopHocPhan")]
	public partial class LopHocPhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLop;
		
		private string _maMon;
		
		private string _phongHoc;
		
		private string _Thu;
		
		private int _TuTiet;
		
		private int _DenTiet;
		
		private string _maGV;
		
		private int _soLuong;
		
		private int _daDK;
		
		private System.DateTime _tgBatDau;
		
		private System.DateTime _tgKetThuc;
		
		private EntitySet<DangKy> _DangKies;
		
		private EntityRef<DanhSachMon> _DanhSachMon;
		
		private EntityRef<GiaoVien> _GiaoVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLopChanging(string value);
    partial void OnmaLopChanged();
    partial void OnmaMonChanging(string value);
    partial void OnmaMonChanged();
    partial void OnphongHocChanging(string value);
    partial void OnphongHocChanged();
    partial void OnThuChanging(string value);
    partial void OnThuChanged();
    partial void OnTuTietChanging(int value);
    partial void OnTuTietChanged();
    partial void OnDenTietChanging(int value);
    partial void OnDenTietChanged();
    partial void OnmaGVChanging(string value);
    partial void OnmaGVChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    partial void OndaDKChanging(int value);
    partial void OndaDKChanged();
    partial void OntgBatDauChanging(System.DateTime value);
    partial void OntgBatDauChanged();
    partial void OntgKetThucChanging(System.DateTime value);
    partial void OntgKetThucChanged();
    #endregion
		
		public LopHocPhan()
		{
			this._DangKies = new EntitySet<DangKy>(new Action<DangKy>(this.attach_DangKies), new Action<DangKy>(this.detach_DangKies));
			this._DanhSachMon = default(EntityRef<DanhSachMon>);
			this._GiaoVien = default(EntityRef<GiaoVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					if (this._DanhSachMon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMonChanging(value);
					this.SendPropertyChanging();
					this._maMon = value;
					this.SendPropertyChanged("maMon");
					this.OnmaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongHoc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string phongHoc
		{
			get
			{
				return this._phongHoc;
			}
			set
			{
				if ((this._phongHoc != value))
				{
					this.OnphongHocChanging(value);
					this.SendPropertyChanging();
					this._phongHoc = value;
					this.SendPropertyChanged("phongHoc");
					this.OnphongHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string Thu
		{
			get
			{
				return this._Thu;
			}
			set
			{
				if ((this._Thu != value))
				{
					this.OnThuChanging(value);
					this.SendPropertyChanging();
					this._Thu = value;
					this.SendPropertyChanged("Thu");
					this.OnThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuTiet", DbType="Int NOT NULL")]
		public int TuTiet
		{
			get
			{
				return this._TuTiet;
			}
			set
			{
				if ((this._TuTiet != value))
				{
					this.OnTuTietChanging(value);
					this.SendPropertyChanging();
					this._TuTiet = value;
					this.SendPropertyChanged("TuTiet");
					this.OnTuTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenTiet", DbType="Int NOT NULL")]
		public int DenTiet
		{
			get
			{
				return this._DenTiet;
			}
			set
			{
				if ((this._DenTiet != value))
				{
					this.OnDenTietChanging(value);
					this.SendPropertyChanging();
					this._DenTiet = value;
					this.SendPropertyChanged("DenTiet");
					this.OnDenTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					if (this._GiaoVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daDK", DbType="Int NOT NULL")]
		public int daDK
		{
			get
			{
				return this._daDK;
			}
			set
			{
				if ((this._daDK != value))
				{
					this.OndaDKChanging(value);
					this.SendPropertyChanging();
					this._daDK = value;
					this.SendPropertyChanged("daDK");
					this.OndaDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgBatDau", DbType="Date NOT NULL")]
		public System.DateTime tgBatDau
		{
			get
			{
				return this._tgBatDau;
			}
			set
			{
				if ((this._tgBatDau != value))
				{
					this.OntgBatDauChanging(value);
					this.SendPropertyChanging();
					this._tgBatDau = value;
					this.SendPropertyChanged("tgBatDau");
					this.OntgBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgKetThuc", DbType="Date NOT NULL")]
		public System.DateTime tgKetThuc
		{
			get
			{
				return this._tgKetThuc;
			}
			set
			{
				if ((this._tgKetThuc != value))
				{
					this.OntgKetThucChanging(value);
					this.SendPropertyChanging();
					this._tgKetThuc = value;
					this.SendPropertyChanged("tgKetThuc");
					this.OntgKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHocPhan_DangKy", Storage="_DangKies", ThisKey="maLop", OtherKey="maLop")]
		public EntitySet<DangKy> DangKies
		{
			get
			{
				return this._DangKies;
			}
			set
			{
				this._DangKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachMon_LopHocPhan", Storage="_DanhSachMon", ThisKey="maMon", OtherKey="maMon", IsForeignKey=true)]
		public DanhSachMon DanhSachMon
		{
			get
			{
				return this._DanhSachMon.Entity;
			}
			set
			{
				DanhSachMon previousValue = this._DanhSachMon.Entity;
				if (((previousValue != value) 
							|| (this._DanhSachMon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhSachMon.Entity = null;
						previousValue.LopHocPhans.Remove(this);
					}
					this._DanhSachMon.Entity = value;
					if ((value != null))
					{
						value.LopHocPhans.Add(this);
						this._maMon = value.maMon;
					}
					else
					{
						this._maMon = default(string);
					}
					this.SendPropertyChanged("DanhSachMon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_LopHocPhan", Storage="_GiaoVien", ThisKey="maGV", OtherKey="maGV", IsForeignKey=true)]
		public GiaoVien GiaoVien
		{
			get
			{
				return this._GiaoVien.Entity;
			}
			set
			{
				GiaoVien previousValue = this._GiaoVien.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVien.Entity = null;
						previousValue.LopHocPhans.Remove(this);
					}
					this._GiaoVien.Entity = value;
					if ((value != null))
					{
						value.LopHocPhans.Add(this);
						this._maGV = value.maGV;
					}
					else
					{
						this._maGV = default(string);
					}
					this.SendPropertyChanged("GiaoVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.LopHocPhan = this;
		}
		
		private void detach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.LopHocPhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSV;
		
		private string _tenSV;
		
		private string _maKhoa;
		
		private string _lop;
		
		private string _nienKhoa;
		
		private EntitySet<DangKy> _DangKies;
		
		private EntityRef<DanhSachKhongDuocDangKy> _DanhSachKhongDuocDangKy;
		
		private EntityRef<Khoa> _Khoa;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OntenSVChanging(string value);
    partial void OntenSVChanged();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    partial void OnlopChanging(string value);
    partial void OnlopChanged();
    partial void OnnienKhoaChanging(string value);
    partial void OnnienKhoaChanged();
    #endregion
		
		public SinhVien()
		{
			this._DangKies = new EntitySet<DangKy>(new Action<DangKy>(this.attach_DangKies), new Action<DangKy>(this.detach_DangKies));
			this._DanhSachKhongDuocDangKy = default(EntityRef<DanhSachKhongDuocDangKy>);
			this._Khoa = default(EntityRef<Khoa>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenSV
		{
			get
			{
				return this._tenSV;
			}
			set
			{
				if ((this._tenSV != value))
				{
					this.OntenSVChanging(value);
					this.SendPropertyChanging();
					this._tenSV = value;
					this.SendPropertyChanged("tenSV");
					this.OntenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this.OnlopChanging(value);
					this.SendPropertyChanging();
					this._lop = value;
					this.SendPropertyChanged("lop");
					this.OnlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nienKhoa", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string nienKhoa
		{
			get
			{
				return this._nienKhoa;
			}
			set
			{
				if ((this._nienKhoa != value))
				{
					this.OnnienKhoaChanging(value);
					this.SendPropertyChanging();
					this._nienKhoa = value;
					this.SendPropertyChanged("nienKhoa");
					this.OnnienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DangKy", Storage="_DangKies", ThisKey="maSV", OtherKey="maSV")]
		public EntitySet<DangKy> DangKies
		{
			get
			{
				return this._DangKies;
			}
			set
			{
				this._DangKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DanhSachKhongDuocDangKy", Storage="_DanhSachKhongDuocDangKy", ThisKey="maSV", OtherKey="maSV", IsUnique=true, IsForeignKey=false)]
		public DanhSachKhongDuocDangKy DanhSachKhongDuocDangKy
		{
			get
			{
				return this._DanhSachKhongDuocDangKy.Entity;
			}
			set
			{
				DanhSachKhongDuocDangKy previousValue = this._DanhSachKhongDuocDangKy.Entity;
				if (((previousValue != value) 
							|| (this._DanhSachKhongDuocDangKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhSachKhongDuocDangKy.Entity = null;
						previousValue.SinhVien = null;
					}
					this._DanhSachKhongDuocDangKy.Entity = value;
					if ((value != null))
					{
						value.SinhVien = this;
					}
					this.SendPropertyChanged("DanhSachKhongDuocDangKy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_Khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_SinhVien", Storage="_TaiKhoan", ThisKey="maSV", OtherKey="tenDangNhap", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.SinhVien = null;
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.SinhVien = this;
						this._maSV = value.tenDangNhap;
					}
					else
					{
						this._maSV = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
	
	public partial class tklhptenmonResult
	{
		
		private string _maMon;
		
		private string _maLop;
		
		private string _tenMon;
		
		private int _soTC;
		
		private string _phongHoc;
		
		private string _thu;
		
		private int _TuTiet;
		
		private int _DenTiet;
		
		private string _TenGV;
		
		private int _soLuong;
		
		private System.DateTime _tgBatDau;
		
		private System.DateTime _tgKetThuc;
		
		public tklhptenmonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongHoc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string phongHoc
		{
			get
			{
				return this._phongHoc;
			}
			set
			{
				if ((this._phongHoc != value))
				{
					this._phongHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thu", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string thu
		{
			get
			{
				return this._thu;
			}
			set
			{
				if ((this._thu != value))
				{
					this._thu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuTiet", DbType="Int NOT NULL")]
		public int TuTiet
		{
			get
			{
				return this._TuTiet;
			}
			set
			{
				if ((this._TuTiet != value))
				{
					this._TuTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenTiet", DbType="Int NOT NULL")]
		public int DenTiet
		{
			get
			{
				return this._DenTiet;
			}
			set
			{
				if ((this._DenTiet != value))
				{
					this._DenTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGV
		{
			get
			{
				return this._TenGV;
			}
			set
			{
				if ((this._TenGV != value))
				{
					this._TenGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgBatDau", DbType="Date NOT NULL")]
		public System.DateTime tgBatDau
		{
			get
			{
				return this._tgBatDau;
			}
			set
			{
				if ((this._tgBatDau != value))
				{
					this._tgBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgKetThuc", DbType="Date NOT NULL")]
		public System.DateTime tgKetThuc
		{
			get
			{
				return this._tgKetThuc;
			}
			set
			{
				if ((this._tgKetThuc != value))
				{
					this._tgKetThuc = value;
				}
			}
		}
	}
	
	public partial class timkiemResult
	{
		
		private string _maMon;
		
		private string _maLop;
		
		private string _tenMon;
		
		private int _soTC;
		
		private string _phongHoc;
		
		private string _thu;
		
		private int _TuTiet;
		
		private int _DenTiet;
		
		private string _TenGV;
		
		private int _soLuong;
		
		private System.DateTime _tgBatDau;
		
		private System.DateTime _tgKetThuc;
		
		public timkiemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongHoc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string phongHoc
		{
			get
			{
				return this._phongHoc;
			}
			set
			{
				if ((this._phongHoc != value))
				{
					this._phongHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thu", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string thu
		{
			get
			{
				return this._thu;
			}
			set
			{
				if ((this._thu != value))
				{
					this._thu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuTiet", DbType="Int NOT NULL")]
		public int TuTiet
		{
			get
			{
				return this._TuTiet;
			}
			set
			{
				if ((this._TuTiet != value))
				{
					this._TuTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenTiet", DbType="Int NOT NULL")]
		public int DenTiet
		{
			get
			{
				return this._DenTiet;
			}
			set
			{
				if ((this._DenTiet != value))
				{
					this._DenTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGV
		{
			get
			{
				return this._TenGV;
			}
			set
			{
				if ((this._TenGV != value))
				{
					this._TenGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgBatDau", DbType="Date NOT NULL")]
		public System.DateTime tgBatDau
		{
			get
			{
				return this._tgBatDau;
			}
			set
			{
				if ((this._tgBatDau != value))
				{
					this._tgBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgKetThuc", DbType="Date NOT NULL")]
		public System.DateTime tgKetThuc
		{
			get
			{
				return this._tgKetThuc;
			}
			set
			{
				if ((this._tgKetThuc != value))
				{
					this._tgKetThuc = value;
				}
			}
		}
	}
	
	public partial class tklhpkhoaResult
	{
		
		private string _maMon;
		
		private string _maLop;
		
		private string _tenMon;
		
		private int _soTC;
		
		private string _phongHoc;
		
		private string _thu;
		
		private int _TuTiet;
		
		private int _DenTiet;
		
		private string _TenGV;
		
		private int _soLuong;
		
		private System.DateTime _tgBatDau;
		
		private System.DateTime _tgKetThuc;
		
		public tklhpkhoaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongHoc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string phongHoc
		{
			get
			{
				return this._phongHoc;
			}
			set
			{
				if ((this._phongHoc != value))
				{
					this._phongHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thu", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string thu
		{
			get
			{
				return this._thu;
			}
			set
			{
				if ((this._thu != value))
				{
					this._thu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuTiet", DbType="Int NOT NULL")]
		public int TuTiet
		{
			get
			{
				return this._TuTiet;
			}
			set
			{
				if ((this._TuTiet != value))
				{
					this._TuTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenTiet", DbType="Int NOT NULL")]
		public int DenTiet
		{
			get
			{
				return this._DenTiet;
			}
			set
			{
				if ((this._DenTiet != value))
				{
					this._DenTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGV
		{
			get
			{
				return this._TenGV;
			}
			set
			{
				if ((this._TenGV != value))
				{
					this._TenGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgBatDau", DbType="Date NOT NULL")]
		public System.DateTime tgBatDau
		{
			get
			{
				return this._tgBatDau;
			}
			set
			{
				if ((this._tgBatDau != value))
				{
					this._tgBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgKetThuc", DbType="Date NOT NULL")]
		public System.DateTime tgKetThuc
		{
			get
			{
				return this._tgKetThuc;
			}
			set
			{
				if ((this._tgKetThuc != value))
				{
					this._tgKetThuc = value;
				}
			}
		}
	}
	
	public partial class tklhpmamonResult
	{
		
		private string _maMon;
		
		private string _maLop;
		
		private string _tenMon;
		
		private int _soTC;
		
		private string _phongHoc;
		
		private string _thu;
		
		private int _TuTiet;
		
		private int _DenTiet;
		
		private string _TenGV;
		
		private int _soLuong;
		
		private System.DateTime _tgBatDau;
		
		private System.DateTime _tgKetThuc;
		
		public tklhpmamonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phongHoc", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string phongHoc
		{
			get
			{
				return this._phongHoc;
			}
			set
			{
				if ((this._phongHoc != value))
				{
					this._phongHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thu", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string thu
		{
			get
			{
				return this._thu;
			}
			set
			{
				if ((this._thu != value))
				{
					this._thu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuTiet", DbType="Int NOT NULL")]
		public int TuTiet
		{
			get
			{
				return this._TuTiet;
			}
			set
			{
				if ((this._TuTiet != value))
				{
					this._TuTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenTiet", DbType="Int NOT NULL")]
		public int DenTiet
		{
			get
			{
				return this._DenTiet;
			}
			set
			{
				if ((this._DenTiet != value))
				{
					this._DenTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGV
		{
			get
			{
				return this._TenGV;
			}
			set
			{
				if ((this._TenGV != value))
				{
					this._TenGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgBatDau", DbType="Date NOT NULL")]
		public System.DateTime tgBatDau
		{
			get
			{
				return this._tgBatDau;
			}
			set
			{
				if ((this._tgBatDau != value))
				{
					this._tgBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgKetThuc", DbType="Date NOT NULL")]
		public System.DateTime tgKetThuc
		{
			get
			{
				return this._tgKetThuc;
			}
			set
			{
				if ((this._tgKetThuc != value))
				{
					this._tgKetThuc = value;
				}
			}
		}
	}
	
	public partial class Chuong_trinh_ngoai_ke_hoachResult
	{
		
		private string _maLop;
		
		private string _tenMon;
		
		private System.Nullable<int> _soTC;
		
		private System.Nullable<int> _soTiet;
		
		private string _loaiMon;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<int> _daDK;
		
		private string _tenGV;
		
		private string _lichHoc;
		
		public Chuong_trinh_ngoai_ke_hoachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20)")]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50)")]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int")]
		public System.Nullable<int> soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTiet", DbType="Int")]
		public System.Nullable<int> soTiet
		{
			get
			{
				return this._soTiet;
			}
			set
			{
				if ((this._soTiet != value))
				{
					this._soTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiMon", DbType="NChar(20)")]
		public string loaiMon
		{
			get
			{
				return this._loaiMon;
			}
			set
			{
				if ((this._loaiMon != value))
				{
					this._loaiMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daDK", DbType="Int")]
		public System.Nullable<int> daDK
		{
			get
			{
				return this._daDK;
			}
			set
			{
				if ((this._daDK != value))
				{
					this._daDK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenGV", DbType="NVarChar(30)")]
		public string tenGV
		{
			get
			{
				return this._tenGV;
			}
			set
			{
				if ((this._tenGV != value))
				{
					this._tenGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lichHoc", DbType="NVarChar(30)")]
		public string lichHoc
		{
			get
			{
				return this._lichHoc;
			}
			set
			{
				if ((this._lichHoc != value))
				{
					this._lichHoc = value;
				}
			}
		}
	}
	
	public partial class Chuong_trinh_dao_taoResult
	{
		
		private string _maMon;
		
		private string _tenMon;
		
		private string _loaiMon;
		
		private int _soTC;
		
		public Chuong_trinh_dao_taoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maMon
		{
			get
			{
				return this._maMon;
			}
			set
			{
				if ((this._maMon != value))
				{
					this._maMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string loaiMon
		{
			get
			{
				return this._loaiMon;
			}
			set
			{
				if ((this._loaiMon != value))
				{
					this._loaiMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
	}
	
	public partial class Chuong_trinh_theo_ke_hoachResult
	{
		
		private string _maLop;
		
		private string _tenMon;
		
		private int _soTC;
		
		private System.Nullable<int> _soTiet;
		
		private string _loaiMon;
		
		private int _soLuong;
		
		private int _daDK;
		
		private string _TenGV;
		
		private string _lichHoc;
		
		public Chuong_trinh_theo_ke_hoachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTiet", DbType="Int")]
		public System.Nullable<int> soTiet
		{
			get
			{
				return this._soTiet;
			}
			set
			{
				if ((this._soTiet != value))
				{
					this._soTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiMon", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string loaiMon
		{
			get
			{
				return this._loaiMon;
			}
			set
			{
				if ((this._loaiMon != value))
				{
					this._loaiMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this._soLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daDK", DbType="Int NOT NULL")]
		public int daDK
		{
			get
			{
				return this._daDK;
			}
			set
			{
				if ((this._daDK != value))
				{
					this._daDK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGV
		{
			get
			{
				return this._TenGV;
			}
			set
			{
				if ((this._TenGV != value))
				{
					this._TenGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lichHoc", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string lichHoc
		{
			get
			{
				return this._lichHoc;
			}
			set
			{
				if ((this._lichHoc != value))
				{
					this._lichHoc = value;
				}
			}
		}
	}
	
	public partial class Mon_dang_kyResult
	{
		
		private string _maLop;
		
		private string _tenMon;
		
		private int _soTC;
		
		private string _tenGV;
		
		private System.DateTime _tgBatDau;
		
		private System.DateTime _tgKetThuc;
		
		public Mon_dang_kyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this._maLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenMon
		{
			get
			{
				return this._tenMon;
			}
			set
			{
				if ((this._tenMon != value))
				{
					this._tenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int NOT NULL")]
		public int soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this._soTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenGV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenGV
		{
			get
			{
				return this._tenGV;
			}
			set
			{
				if ((this._tenGV != value))
				{
					this._tenGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgBatDau", DbType="Date NOT NULL")]
		public System.DateTime tgBatDau
		{
			get
			{
				return this._tgBatDau;
			}
			set
			{
				if ((this._tgBatDau != value))
				{
					this._tgBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgKetThuc", DbType="Date NOT NULL")]
		public System.DateTime tgKetThuc
		{
			get
			{
				return this._tgKetThuc;
			}
			set
			{
				if ((this._tgKetThuc != value))
				{
					this._tgKetThuc = value;
				}
			}
		}
	}
	
	public partial class dskhongdkResult
	{
		
		private string _maSV;
		
		private string _tenSV;
		
		private string _tenKhoa;
		
		private string _lop;
		
		private string _nienKhoa;
		
		private string _ghiChu;
		
		public dskhongdkResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this._maSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenSV
		{
			get
			{
				return this._tenSV;
			}
			set
			{
				if ((this._tenSV != value))
				{
					this._tenSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhoa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenKhoa
		{
			get
			{
				return this._tenKhoa;
			}
			set
			{
				if ((this._tenKhoa != value))
				{
					this._tenKhoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this._lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nienKhoa", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string nienKhoa
		{
			get
			{
				return this._nienKhoa;
			}
			set
			{
				if ((this._nienKhoa != value))
				{
					this._nienKhoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this._ghiChu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
